### ISSUE TITLE
Adding multiple directory for route definition

### ISSUE THREAD

**Issue by helyakin** [api-scout/api-scout#12]
```yaml
mapping:
  paths: 
    - '%kernel.project_dir%/src/Controller'
    - '%kernel.project_dir%/src/OtherController
```
